---
title: "Homework 4"
date: "Due June 12, 2017 in class"
output: 
  pdf_document:
    number_sections: true
geometry: margin=1in
---

Please show all work for full credit. Print and staple your assignment together and submit by end of class the due date. If you cannot attend class on the due date, please arrange to submit your homework prior to the due date.

```{r setup, echo=FALSE, message=FALSE}
library(knitr)
library(tidyverse)
library(xtable)

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, fig.height = 2)
theme_set(theme_bw(base_family = "serif"))
```

1. [Ch. 5.1, Exercise 6, pg. 244] Suppose that an eddy current nondestructive evaluation technique for identifying cracks in critical metal parts has a probability of about $.20$ of detecting a single crack of length $.003$in. in a certain material. Let $Y$ be the number of specimens inspected in order to obtain the first crack detection. Use an appropriate probability model and evaluate all of the following:
    a) $P[Y = 5]$
    b) $P[Y \le 4]$
    c) $\text{E}Y$
    d) $\text{Var}Y$
    e) $\text{SD}(Y)$
    
1. [Ch. 5.1, Exercise 9, pg. 244] Transmission line interruptions in a telecommunication network occur at an average rate of one per day.
    a) Use a Poisson distribution as a model for
        $$
        X = \text{the number of interruptions in the next five-day work week}
        $$
        
        and assess $P[X = 0]$
    b) Now consider the random variable
        $$
        Y = \text{the number of work weeks in the next four in which there are no interruptions}
        $$
        What is a reasonable probability model for $Y$? Assess $P[Y = 2]$.

1. [Ch. 5.2, Exercise 1, pg. 263] The random number generator supplied on a calculator is not terribly well chosen, in that values it generates are not adequately described by a uniform distribution on the interval $(0,1)$. Suppose instead that a probability density
    $$
    f(x) = \begin{cases} k(5 - x) & 0 < x< 1 \\ 0 & \text{otherwise}\end{cases}
    $$
    
    is a more appropriate model for $X =$ the next value produced by this random number generator.
    
    a) Find the value of $k$
    b) Sketch the probability density involved here.
    c) Evaluate $P[.25 < X < .75]$
    d) Compute and graph the cumulative probability distribution function for $X$, $F(x)$.
    e) Calculate $\text{E}X$ and the standard deviation of $X$.
    
1. The mileage to first failure for a model of military personnel carrier can be modeled as exponential with mean $1,000$ miles.
    a) Evaluate the probability that a vehicle of this type gives less than $500$ miles of service before first failure. Evaluate the probability that a vehicle of this type gives less than $2000$ miles of service before first failure. 
    b) Find the $.05$ quantile of the distribution of mileage to first failure. Then find the $.9$ quantile of the distribution.
    
1. [Ch. 5.2, Exercise 2, pg. 263] Suppose that $Z$ is a standard normal random variable. Evaluate the following probabilities involving $Z$:
    a) $P[Z < -.62]$
    a) $P[Z > 1.06]$
    a) $P[-.37 < Z < .51]$
    a) $P[|Z| \le .47]$
    a) $P[|Z| > .93]$
    a) $P[-3.0 < Z < 3.0]$
    
    Now find numbers # such that the following statements involving $Z$ are true:
    
    g) $P[Z \le \#] = .90$
    g) $P[|Z| \le \#] = .90$
    g) $P[|Z| > \#] = .03$
    
1. [Ch. 5.2, Exercise 3, pg. 263] Suppose that $X$ is a normal random variable with mean $43$ and standard deviation $3.6$. Evaluate the following probabilities involving $X$:
    a) $P[X < 45.2]$
    a) $P[X \le 41.7]$
    a) $P[43.8 < X \le 47.0]$
    a) $P[|X - 43| \le 2]$
    a) $P[|X - 43| > 1.7]$
    
    Now find numbers # such that the following statements involving $X$ are true:
    
    f) $P[X < \#] = .95$
    g) $P[X \ge \#] = .30$
    h) $P[|X - 43| > \#] = .05$