---
output: 
  pdf_document:
    number_sections: true
    includes:
      in_header: 00_header.tex
fontsize: 12pt
geometry: margin=1in
---

\setcounter{section}{0}

# Introduction

First we start with a roadmap for the course. The subject of **engineering statistics** is defined, its importance is described and basic terminology is introduced.

## What is statistics?

Statistics is the science of collecting, presenting, analyzing, and making decisions from data. Often, as an engineer, it is necessary to **collect and interpret data** that will help in understanding how a new system or product works. 

Statistics has applications to engineering through 

- quality control, 
- process control, 
- reliability, 
- risk management, 
- system identification, 
- design of experiments, etc.

\vspace{.25in}
\begin{df}
\emph{Engineering statistics} is the study of how best to 
\begin{enumerate}
\item collect engineering data,
\item summarize or describe engineering data, and
\item draw formal inference and practical conclusions on the basis of engineering data,
\end{enumerate}
all while recognizing the reality of variation.
\end{df}
\vspace{.25in}

We can break down this study into three main tasks:

\begin{enumerate}
\itemsep .1in
\item {\bf Summary:} 
\item {\bf Inference:}
\item {\bf Interpretation:}
\end{enumerate}

\newpage

\begin{ex}[Heat treating gears, pg. 2]

\end{ex}

## Populations and samples

## Experimental vs. observational studies

## Data and measurement

## Complete/Fractional factorial designs
