<br/>

# Lectures

[Carver Hall 0274](http://www.fpm.iastate.edu/roomscheduling/room.asp?room_id=51)  
Mon Tue Wed Thu Fri 9:50 AM - 10:50 AM
No class on Mon, May 29 or Tues, July 4 (University Holiday).   

<iframe src="https://calendar.google.com/calendar/embed?src=iastate.edu_car6h4lm1hgecaiejjuehb3r1c%40group.calendar.google.com&amp;mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;ctz=America%2FChicago" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>

# Topics

Week | Topic | Blank Notes | Filled Notes | Comments
--- | ---------------------- | -------- | -------- | -------- 
1  | Introduction, Data collection, Descriptive statistics (Ch. 1-2, 3.1-3.2) | [Ch. 1](notes/blank/01_introduction.pdf) <br/> [Ch. 2](notes/blank/02_collection.pdf) <br/> [Ch. 3](notes/blank/03_descriptive.pdf) | [Monday](notes/filled/05_15_2017_01.pdf) [Tuesday pt. 1](notes/filled/05_16_2017_01.pdf) <br/> [Tuesday pt. 2](notes/filled/05_16_2017_02.pdf) [Wednesday](notes/filled/05_17_2017_01.pdf) <br/> [Thursday pt. 1](notes/filled/05_18_2017_01.pdf) <br/> [Thursday pt. 2](notes/filled/05_18_2017_02.pdf) <br/> [Friday](notes/filled/05_19_2017_01.pdf) | [Homework 1](homework/01.pdf) assigned
2  | Descriptive statistics, Line fitting (Ch. 3.2-3.4, 4.1) | [Ch. 4](notes/blank/04_relationships.pdf) <br/> | [Monday](notes/filled/05_22_2017_01.pdf) <br/> [Tuesday](notes/filled/05_23_2017_01.pdf) <br/> [Wednesday pt. 1](notes/filled/05_24_2017_01.pdf) <br/> [Wednesday pt. 2](notes/filled/05_24_2017_02.pdf) <br/> [Thursday](notes/filled/05_25_2017_01.pdf) <br/> [Friday](notes/filled/05_26_2017_01.pdf)| [Homework 2](homework/02.pdf) assigned
3  | Curve and surface fitting, Random variables (Ch. 4.2, 5.1) | [Ch. 5](notes/blank/05_probability.pdf) <br/> | [Tuesday](notes/filled/05_30_2017_01.pdf) <br/> [Wednesday pt. 1](notes/filled/05_31_2017_01.pdf) <br/> [Wednesday pt. 2](notes/filled/05_31_2017_02.pdf) <br/> [Thursday](notes/filled/06_01_2017_01.pdf) <br/> [Friday](notes/filled/06_02_2017_01.pdf) <br/>| [Homework 3](homework/03.pdf) assigned
4  | Random variables (Ch. 5.2, 5.4) |  | [Tuesday](notes/filled/06_06_2017_01.pdf) <br/> [Wednesday](notes/filled/06_07_2017_01.pdf) <br/> [Thursday](notes/filled/06_08_2017_01.pdf) <br/> [Friday](notes/filled/06_09_2017_01.pdf) <br/> | [Homework 4](homework/04.pdf) assigned
5  | Random variables (Ch. 5.4, 5.5) |  | [Monday](notes/filled/06_12_2017_01.pdf) <br/> [Tuesday](notes/filled/06_13_2017_01.pdf) <br/> | [Homework 5](homework/05.pdf) assigned
6  | Simple inference, (Ch. 6.1-6.2) |  |  |
7  | Hypothesis testing, Inference for SLR (Ch.6.3, 6.6, 9.1) |  |  |   
8  | Inference for MLR (Ch. 9.2) |  |  | 

# Homework

1. [Homework 1](homework/01.pdf) - due May 22
2. [Homework 2](homework/02.pdf) - due May 30
3. [Homework 3](homework/03.pdf) - due June 2
4. [Homework 4](homework/04.pdf) - due June 12
5. [Homework 5](homework/05.pdf) - due June 19
<!--
6. [Homework 6](homework/06.pdf) - due June 23
7. [Homework 7](homework/07.pdf) - due July 3 
-->

# Exams

Exams will be held on the evening (6 - 8pm) of the follwing dates. On exam days there will be no in-class lecture. If you have a conflict, please notify the instructor at least **one week in advance** to reschedule.

```{r, echo=FALSE}
exams <- data.frame(Exam = c("Exam 1", "Exam 2", "Final Exam**"),
                    Date = c("June 5", "June 26", "July 7"),
                    Location = c("Gilman 2272", "Carver 0274", "Carver 0274"),
                    Topics = c("Ch. 1-4", "Ch. 5", "Ch. 1-6, 9"))

knitr::kable(exams)
```


### Exam 1

[Topic outline](exams/practice/exam_1_topics.pdf)  
[Practice exam](exams/practice/exam_1_practice.pdf)

<!--
### Exam 2

[Topic outline](exams/practice/exam_2_topics.pdf)  
[Practice exam](exams/practice/exam_2_practice.pdf)

### Final Exam

[Topic outline](exams/practice/exam_3_topics.pdf)  
[Practice exam](exams/practice/exam_3_practice.pdf)
-->

# JMP

[Installation instructions](admin/jmp_install.pdf)

# Tables

[Random digits](tables/random-digits.pdf)  

<!--
[Standard Normal cumulative probabilities](tables/standard-normal.pdf)  
[Student's t quantiles](tables/t.pdf)
-->

# Data
[bolts.csv](data/bolts.csv)  
[bullets.csv](data/bullets.csv)    
[cars.csv](data/cars.csv)   
[cylinders.csv](data/cylinders.csv)    
[gears.csv](data/gears.csv)  
[manganese.csv](data/manganese.csv)  
[officehours.csv](data/officehours.csv)  
[orangetrees.csv](data/orangetrees.csv)   
[paper.csv](data/paper.csv)  
[plastics.csv](data/plastics.csv)  
[pulp.csv](data/pulp.csv)  
[rivers.csv](data/rivers.csv)  
[stackloss.csv](data/stackloss.csv)  
[polyols.csv](data/polyols.csv)  
[tool_life.csv](data/tool_life.csv)  
[tool_life_full.csv](data/tool_life_full.csv)  
[towels.csv](data/towels.csv)

