---
title: "Homework 1"
date: "Due January 19, 2017 at 5pm in Snedecor 2404"
output: 
  pdf_document:
    number_sections: true
geometry: margin=1in
---

Please show all work for full credit. Print and staple your assignment together and submit by 5pm of the due date in Snedecor 2404. If you cannot attend class or office hours on the due date, please arrange to submit your homework prior to the due date.

1. [Ch. 1.1 Exercise 1, pg. 4] Explain why engineering practice is an inherently statistical enterprise.

1. [Ch. 1.2 Exercise 1, pg. 13] Describe a situation in your field where an observational study might be used to answer a question of real importance. Describe another situation where an experiment might be used.

1. [Ch. 1.2 Exercise 2, pg. 13] Describe two different contexts in your field where, respectively, qualitative and quantitative data might arise.

1. [Ch. 1.2 Exercise 4, pg. 13] Describe a situation in your field where pared data might arise.

1. [Ch. 1.3 Exercise 1, pg. 19] Why might it be argued that in terms of producing useful measurements, one must deal first with the issue of validity, then the issue of precision, and only then the issue of accuracy?

1. [Ch 1.4 Exercise 8, pg. 24] Consider a situation like that of Example 1.1 in the notes (involving the heat treatment of gears). Suppose that the original gears can be purchased from a variety of vendors, they can be made out of a variety of materials, they can be heated according to a variety of regimens (involving different times and temperatures), they can be cooled in a number of different ways, and the furnace atmosphere can be adjusted to a variety of different conditions. A number of features of the final gears are of interest, including their flatness, their concentricity, their hardness (both before and after heat treating), and their surface finish.
    a) What kind of data arise if, for a single set of conditions, the Rockwell hardness of several gears is measures both before and after head treating? (Use the terminology of Section 1.2.) In the same context, suppose that engineering specifications on flatness require that measured flatness exceed .40mm. If flatness is measured for several gears and each gear is simply marked Acceptable or Not Acceptable, what kind of data are generated?
    b) Describe a three-factor full factorial study that might be carried out in this situation. Name the factors that will be used and describe the levels of each. Write out a list of all the different combinations of levels of the factors that will be studied.
